2024-02-20 16:27:45,254 - server - serve - line:76 - INFO - Started server process [29]
2024-02-20 16:27:45,254 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:27:45,256 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:27:45,261 - exception_handlers - http_exception_handler - line:43 - ERROR - 172.19.0.1:34686 - "GET /v2/error-http" 500 Internal Server Error => [HTTPException: Another test]
2024-02-20 16:27:45,262 - exception_handlers - unhandled_exception_handler - line:61 - ERROR - 172.19.0.1:34686 - "GET /v2/error-http" 500 Internal Server Error => [AttributeError: '_SlackBot' object has no attribute 'post_msg']
2024-02-20 16:27:45,264 - h11_impl - run_asgi - line:413 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 91, in receive_nowait
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/dice_and_die_api/app/infrastructure/logs/middleware.py", line 18, in log_request_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 88, in __call__
    response = await handler(request, exc)
  File "/dice_and_die_api/app/infrastructure/logs/exception_handlers.py", line 45, in http_exception_handler
    slack_bot.post_msg(log_msg)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: '_SlackBot' object has no attribute 'post_msg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 174, in __call__
    response = await self.handler(request, exc)
  File "/dice_and_die_api/app/infrastructure/logs/exception_handlers.py", line 63, in unhandled_exception_handler
    slack_bot.post_msg(log_msg)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: '_SlackBot' object has no attribute 'post_msg'
2024-02-20 16:28:20,355 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 16:28:20,457 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 16:28:20,458 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 16:28:20,458 - server - serve - line:86 - INFO - Finished server process [29]
2024-02-20 16:28:22,705 - server - serve - line:76 - INFO - Started server process [30]
2024-02-20 16:28:22,705 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:28:22,706 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:28:23,132 - exception_handlers - http_exception_handler - line:43 - ERROR - 172.19.0.1:36406 - "GET /v2/error-http" 500 Internal Server Error => [HTTPException: Another test]
2024-02-20 16:28:23,566 - middleware - log_request_middleware - line:29 - INFO - 172.19.0.1:36406 - "GET /v2/error-http" 500 Internal Server Error 434.22ms
2024-02-20 16:41:02,428 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 16:41:02,530 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 16:41:02,531 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 16:41:02,531 - server - serve - line:86 - INFO - Finished server process [30]
2024-02-20 16:50:11,089 - server - serve - line:76 - INFO - Started server process [36]
2024-02-20 16:50:11,090 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:50:11,091 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:50:18,212 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 16:50:18,314 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 16:50:18,315 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 16:50:18,315 - server - serve - line:86 - INFO - Finished server process [36]
2024-02-20 16:50:20,905 - server - serve - line:76 - INFO - Started server process [37]
2024-02-20 16:50:20,905 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:50:20,906 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:50:24,793 - exception_handlers - http_exception_handler - line:43 - ERROR - 172.19.0.1:58434 - "GET /v2/error-http" 500 Internal Server Error => [HTTPException: Another test]
2024-02-20 16:50:25,190 - middleware - log_request_middleware - line:29 - INFO - 172.19.0.1:58434 - "GET /v2/error-http" 500 Internal Server Error 397.53ms
2024-02-20 16:51:31,060 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 16:51:31,161 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 16:51:31,162 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 16:51:31,163 - server - serve - line:86 - INFO - Finished server process [37]
2024-02-20 16:51:33,431 - server - serve - line:76 - INFO - Started server process [38]
2024-02-20 16:51:33,432 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:51:33,432 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:51:35,336 - exception_handlers - http_exception_handler - line:43 - ERROR - 172.19.0.1:39868 - "GET /v2/error-http" 500 Internal Server Error => [HTTPException: Another test]
2024-02-20 16:51:35,789 - middleware - log_request_middleware - line:29 - INFO - 172.19.0.1:39868 - "GET /v2/error-http" 500 Internal Server Error 453.42ms
2024-02-20 16:56:05,288 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 16:56:05,389 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 16:56:05,390 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 16:56:05,390 - server - serve - line:86 - INFO - Finished server process [38]
2024-02-20 16:58:48,365 - server - serve - line:76 - INFO - Started server process [40]
2024-02-20 16:58:48,366 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:58:48,366 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:59:52,640 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 16:59:52,741 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 16:59:52,742 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 16:59:52,742 - server - serve - line:86 - INFO - Finished server process [40]
2024-02-20 16:59:55,118 - server - serve - line:76 - INFO - Started server process [41]
2024-02-20 16:59:55,118 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 16:59:55,119 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 16:59:59,183 - logger - handle_unhandled_exception - line:80 - ERROR - 172.19.0.1:36634 - "GET /v2/error-http" 500 Internal Server Error => [AttributeError: 'LoggerConfigurator' object has no attribute 'logger']
2024-02-20 16:59:59,654 - h11_impl - run_asgi - line:413 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/dice_and_die_api/app/infrastructure/logs/middleware.py", line 15, in log_request_middleware
    logger_conf.logger.debug("middleware: log_request_middleware")
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'LoggerConfigurator' object has no attribute 'logger'
2024-02-20 17:01:01,648 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:01:01,749 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:01:01,750 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:01:01,750 - server - serve - line:86 - INFO - Finished server process [41]
2024-02-20 17:01:04,093 - server - serve - line:76 - INFO - Started server process [42]
2024-02-20 17:01:04,093 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:01:04,094 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 17:01:06,096 - logger - handle_unhandled_exception - line:80 - ERROR - 172.19.0.1:35890 - "GET /v2/error-http" 500 Internal Server Error => [AttributeError: 'LoggerConfigurator' object has no attribute 'logger']
2024-02-20 17:01:06,444 - h11_impl - run_asgi - line:413 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/dice_and_die_api/app/infrastructure/logs/middleware.py", line 15, in log_request_middleware
    logger_conf.logger.debug("middleware: log_request_middleware")
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'LoggerConfigurator' object has no attribute 'logger'
2024-02-20 17:01:41,153 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:01:41,254 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:01:41,254 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:01:41,255 - server - serve - line:86 - INFO - Finished server process [42]
2024-02-20 17:01:43,498 - server - serve - line:76 - INFO - Started server process [43]
2024-02-20 17:01:43,499 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:01:43,500 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 17:01:47,341 - logger - handle_http_exception - line:69 - ERROR - 172.19.0.1:43880 - "GET /v2/error-http" 500 Internal Server Error => [HTTPException: Another test]
2024-02-20 17:01:47,759 - middleware - log_request_middleware - line:29 - INFO - 172.19.0.1:43880 - "GET /v2/error-http" 500 Internal Server Error 417.76ms
2024-02-20 17:39:03,122 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:39:03,223 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:39:03,224 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:39:03,224 - server - serve - line:86 - INFO - Finished server process [43]
2024-02-20 17:39:06,022 - server - serve - line:76 - INFO - Started server process [44]
2024-02-20 17:39:06,022 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:39:06,023 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 17:39:51,638 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:39:51,739 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:39:51,740 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:39:51,740 - server - serve - line:86 - INFO - Finished server process [44]
2024-02-20 17:39:54,508 - server - serve - line:76 - INFO - Started server process [45]
2024-02-20 17:39:54,509 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:39:54,510 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 17:47:04,650 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:47:04,751 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:47:04,752 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:47:04,753 - server - serve - line:86 - INFO - Finished server process [45]
2024-02-20 17:47:07,036 - server - serve - line:76 - INFO - Started server process [46]
2024-02-20 17:47:07,036 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:47:07,037 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 17:51:10,878 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:51:10,979 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:51:10,980 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:51:10,981 - server - serve - line:86 - INFO - Finished server process [46]
2024-02-20 17:51:13,565 - server - serve - line:76 - INFO - Started server process [47]
2024-02-20 17:51:13,629 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:51:13,638 - on - startup - line:60 - INFO - Application startup complete.
2024-02-20 17:51:14,745 - logger - handle_http_exception - line:68 - ERROR - 172.19.0.1:53678 - "GET /v2/error-http" 500 Internal Server Error => [HTTPException: Another test]
2024-02-20 17:51:15,232 - middleware - log_request_middleware - line:29 - INFO - 172.19.0.1:53678 - "GET /v2/error-http" 500 Internal Server Error 487.70ms
2024-02-20 17:58:56,974 - server - shutdown - line:264 - INFO - Shutting down
2024-02-20 17:58:57,075 - on - shutdown - line:65 - INFO - Waiting for application shutdown.
2024-02-20 17:58:57,076 - on - shutdown - line:76 - INFO - Application shutdown complete.
2024-02-20 17:58:57,077 - server - serve - line:86 - INFO - Finished server process [47]
2024-02-20 17:58:59,566 - server - serve - line:76 - INFO - Started server process [48]
2024-02-20 17:58:59,567 - on - startup - line:46 - INFO - Waiting for application startup.
2024-02-20 17:58:59,568 - on - startup - line:60 - INFO - Application startup complete.
